// GENERATED by scripts/generate_starter_questions.py — do not edit by hand.
// Sources: eval/saas_gold.py ANSWERABLE, eval/archive_chinook/gold_queries.py
// GOLD_QUERIES, semantic/metrics.yaml metric questions (curated first).
// Regenerate: python scripts/generate_starter_questions.py

/** One starter question and where it came from (W2 N6). */
export interface StarterQuestion {
  question: string;
  source: "fewshot" | "semantic";
}

/** Corpus-derived starters per target group; the UI picks by the active
 *  target's database name (the guardrails manifest). */
export const STARTERS_BY_TARGET: {
  saas: StarterQuestion[];
  chinook: StarterQuestion[];
} = {
  saas: [
    { question: "What is our monthly recurring revenue?", source: "semantic" },
    { question: "How much money have we collected in total?", source: "semantic" },
    { question: "How much money is owed to us in open invoices?", source: "semantic" },
    { question: "How many organizations have churned?", source: "semantic" },
    { question: "Which event types do we see most in usage events?", source: "semantic" },
    { question: "How many seats do we have across subscriptions by status?", source: "semantic" },
    { question: "How many organizations are there?", source: "fewshot" },
    { question: "List all plan names.", source: "fewshot" },
  ],
  chinook: [
    { question: "List tracks longer than 5 minutes with their duration.", source: "fewshot" },
    { question: "Show all customers from Brazil.", source: "fewshot" },
    { question: "Show all invoices from 2021.", source: "fewshot" },
    { question: "Show tracks priced above $0.99.", source: "fewshot" },
    { question: "List employees hired after January 1st 2003.", source: "fewshot" },
    { question: "How many tracks does each genre have?", source: "fewshot" },
    { question: "What is the total revenue by billing country?", source: "fewshot" },
    { question: "What is the average track duration for each genre?", source: "fewshot" },
  ],
};
