"""W2 N6 — the committed starters module stays in sync with the corpora.

``web/lib/starterQuestions.generated.ts`` is generated by
``scripts/generate_starter_questions.py`` from the few-shot corpus files and
the semantic metrics. These tests rebuild the module and compare, so editing
a corpus without regenerating fails loudly instead of silently drifting from
what the UI offers.
"""

import importlib.util
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
SCRIPT = ROOT / "scripts" / "generate_starter_questions.py"
GENERATED = ROOT / "web" / "lib" / "starterQuestions.generated.ts"


def _load_generator() -> Any:
    spec = importlib.util.spec_from_file_location(
        "generate_starter_questions", SCRIPT
    )
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def test_generated_starters_module_matches_the_corpora() -> None:
    gen = _load_generator()
    assert GENERATED.exists(), (
        "starter module missing — run python scripts/generate_starter_questions.py"
    )
    assert gen.build_module() == GENERATED.read_text(encoding="utf-8")


def test_starters_are_capped_deduplicated_and_sourced() -> None:
    gen = _load_generator()
    starters = gen.build_starters()
    for group, rows in starters.items():
        assert 0 < len(rows) <= gen.STARTER_CAP, f"{group} cap violated"
        keys = [row["question"].lower() for row in rows]
        assert len(keys) == len(set(keys)), f"{group} has duplicates"
        for row in rows:
            assert row["source"] in ("fewshot", "semantic")
