"""Generate ``web/lib/starterQuestions.generated.ts`` from the committed corpora.

W2 N6 — starter questions on the empty state, derived from the SAME sources the
few-shot corpus is seeded from (``nixus/semantic/seeding.py`` DEFAULT_SOURCES)
plus the semantic-layer metrics' curated questions:

  · ``eval/saas_gold.py`` ANSWERABLE questions    → the ``saas`` group
  · ``eval/archive_chinook/gold_queries.py``      → the ``chinook`` group
  · ``semantic/metrics.yaml`` metric questions    → prepended (curated, and
    verified against the SaaS demo schema by eval/test_metric_questions.py)

Deterministic order, deduplicated case-insensitively, capped per group
(STARTER_CAP). The output is committed and guarded by
``tests/test_starter_questions_sync.py``, which rebuilds the module and
compares — edit the corpora and re-run this script, never the generated file.

Usage: ``python scripts/generate_starter_questions.py``  (writes the file)
"""
from __future__ import annotations

import importlib.util
import json
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
OUT_PATH = ROOT / "web" / "lib" / "starterQuestions.generated.ts"
STARTER_CAP = 8


def _load_module(path: Path, name: str) -> Any:
    """Import a corpus file as a module — robust to packages/namespaces."""
    spec = importlib.util.spec_from_file_location(name, path)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"could not load {path}")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def _metric_questions(yaml_path: Path) -> list[str]:
    """The FIRST (canonical) phrasing of each curated semantic metric."""
    import yaml

    data = yaml.safe_load(yaml_path.read_text(encoding="utf-8")) or {}
    questions: list[str] = []
    for metric in data.get("metrics") or []:
        first = (metric.get("questions") or [None])[0]
        if isinstance(first, str) and first.strip():
            questions.append(" ".join(first.split()))
    return questions


def _corpus_questions(path: Path, list_name: str) -> list[str]:
    """The ``question`` field of every row in a corpus list, in file order."""
    module = _load_module(path, f"nixus_starters_{list_name}")
    questions: list[str] = []
    for row in getattr(module, list_name, []):
        q = row.get("question") if isinstance(row, dict) else None
        if isinstance(q, str) and q.strip():
            questions.append(" ".join(q.split()))
    return questions


def build_starters() -> dict[str, list[dict[str, str]]]:
    """The deduplicated, capped starters per target group."""
    semantic = _metric_questions(ROOT / "semantic" / "metrics.yaml")
    saas_corpus = _corpus_questions(ROOT / "eval" / "saas_gold.py", "ANSWERABLE")
    chinook_corpus = _corpus_questions(
        ROOT / "eval" / "archive_chinook" / "gold_queries.py", "GOLD_QUERIES"
    )

    def dedup_cap(items: list[tuple[str, str]]) -> list[dict[str, str]]:
        seen: set[str] = set()
        out: list[dict[str, str]] = []
        for question, source in items:
            key = question.lower()
            if key in seen:
                continue
            seen.add(key)
            out.append({"question": question, "source": source})
            if len(out) >= STARTER_CAP:
                break
        return out

    return {
        # Curated metric questions lead; the corpus fills the rest, easiest first.
        "saas": dedup_cap(
            [(q, "semantic") for q in semantic] + [(q, "fewshot") for q in saas_corpus]
        ),
        "chinook": dedup_cap([(q, "fewshot") for q in chinook_corpus]),
    }


def _ts(s: str) -> str:
    """A JSON string literal is a valid TypeScript string literal."""
    return json.dumps(s, ensure_ascii=False)


def build_module() -> str:
    """The full generated TypeScript module as a string (deterministic)."""
    starters = build_starters()
    lines = [
        "// GENERATED by scripts/generate_starter_questions.py — do not edit by hand.",
        "// Sources: eval/saas_gold.py ANSWERABLE, eval/archive_chinook/gold_queries.py",
        "// GOLD_QUERIES, semantic/metrics.yaml metric questions (curated first).",
        "// Regenerate: python scripts/generate_starter_questions.py",
        "",
        "/** One starter question and where it came from (W2 N6). */",
        "export interface StarterQuestion {",
        "  question: string;",
        '  source: "fewshot" | "semantic";',
        "}",
        "",
        "/** Corpus-derived starters per target group; the UI picks by the active",
        " *  target's database name (the guardrails manifest). */",
        "export const STARTERS_BY_TARGET: {",
        "  saas: StarterQuestion[];",
        "  chinook: StarterQuestion[];",
        "} = {",
    ]
    for group in ("saas", "chinook"):
        lines.append(f"  {group}: [")
        for starter in starters[group]:
            lines.append(
                f"    {{ question: {_ts(starter['question'])}, "
                f"source: {_ts(starter['source'])} }},"
            )
        lines.append("  ],")
    lines.append("};")
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    OUT_PATH.write_text(build_module(), encoding="utf-8")
    print(f"wrote {OUT_PATH}")


if __name__ == "__main__":
    main()
